// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BabyHaven.Repositories.Models;

public partial class Alert
{
    [Key]
    public int AlertId { get; set; }

    public int GrowthRecordId { get; set; }

    public DateTime AlertDate { get; set; }

    public int DiseaseId { get; set; }

    public string Message { get; set; }

    public bool IsRead { get; set; }

    public string SeverityLevel { get; set; }

    public bool IsAcknowledged { get; set; }

    public virtual Disease Disease { get; set; }

    public virtual GrowthRecord GrowthRecord { get; set; }
}