// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class Blog
{
    public int BlogId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public Guid AuthorId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string Status { get; set; }

    public int CategoryId { get; set; }

    public string Tags { get; set; }

    public string ReferenceSources { get; set; }

    public virtual UserAccount Author { get; set; }

    public virtual ICollection<BlogApproval> BlogApprovals { get; set; } = new List<BlogApproval>();

    public virtual ICollection<BlogReference> BlogReferences { get; set; } = new List<BlogReference>();

    public virtual BlogCategory Category { get; set; }
}