// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class BlogReference
{
    public int ReferenceId { get; set; }

    public int BlogId { get; set; }

    public string ReferenceText { get; set; }

    public string ReferenceUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Blog Blog { get; set; }
}