// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class BlogApproval
{
    public int ApprovalId { get; set; }

    public int BlogId { get; set; }

    public DateTime ApprovalDate { get; set; }

    public string ApprovalStatus { get; set; }

    public string RejectionReason { get; set; }

    public virtual Blog Blog { get; set; }
}