// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BabyHaven.Repositories.Models;

public partial class BmiPercentile
{
    public int Age { get; set; }

    public string Gender { get; set; }

    public double L { get; set; }

    public double M { get; set; }

    public double S { get; set; }

    public double P01 { get; set; }

    public double P50 { get; set; }

    public double P75 { get; set; }

    public double P99 { get; set; }
}