// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BabyHaven.Repositories.Models;

public partial class ConsultationRequest
{
    [Key]
    public int RequestId { get; set; }

    public Guid MemberId { get; set; }

    public Guid ChildId { get; set; }

    public int DoctorId { get; set; }

    public DateTime RequestDate { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public string Urgency { get; set; }

    public string Attachments { get; set; }

    public string Category { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool? IsActive { get; set; }

    public virtual Child Child { get; set; }

    public virtual ConsultationResponse ConsultationResponse { get; set; }

    public virtual Member Member { get; set; }
    public virtual Doctor Doctor { get; set; }

}