// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class DevelopmentalRecord
{
    public int DevelopmentalRecordId { get; set; }

    public int RecordId { get; set; }

    public string ImmunizationStatus { get; set; }

    public string MentalHealthStatus { get; set; }

    public double? GrowthHormoneLevel { get; set; }

    public string AttentionSpan { get; set; }

    public string NeurologicalReflexes { get; set; }

    public string DevelopmentalMilestones { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual GrowthRecord Record { get; set; }
}