// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class Disease
{
    public int DiseaseId { get; set; }

    public string DiseaseName { get; set; }

    public double LowerBoundMale { get; set; }

    public double UpperBoundMale { get; set; }

    public double LowerBoundFemale { get; set; }

    public double UpperBoundFemale { get; set; }

    public int MinAge { get; set; }

    public int MaxAge { get; set; }

    public string Severity { get; set; }

    public string DiseaseType { get; set; }

    public string Symptoms { get; set; }

    public string Treatment { get; set; }

    public string Prevention { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime LastModified { get; set; }

    public string Description { get; set; }

    public string Notes { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Alert> Alerts { get; set; } = new List<Alert>();
}