// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BabyHaven.Repositories.Models;

public partial class DoctorSpecialization
{
    [Key]
    public int DoctorSpecializationId { get; set; }

    public int DoctorId { get; set; }

    public int SpecializationId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual Specialization Specialization { get; set; }
}