// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class GrowthRecord
{
    public int RecordId { get; set; }

    public Guid ChildId { get; set; }

    public Guid RecordedBy { get; set; }

    public int AgeAtRecord { get; set; }

    public string Status { get; set; }

    public bool? Verified { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Alert> Alerts { get; set; } = new List<Alert>();

    public virtual ICollection<BasicGrowthRecord> BasicGrowthRecords { get; set; } = new List<BasicGrowthRecord>();

    public virtual Child Child { get; set; }

    public virtual ICollection<DevelopmentalRecord> DevelopmentalRecords { get; set; } = new List<DevelopmentalRecord>();

    public virtual ICollection<Milestone> Milestones { get; set; } = new List<Milestone>();

    public virtual ICollection<NutritionalRecord> NutritionalRecords { get; set; } = new List<NutritionalRecord>();

    public virtual ICollection<PhysiologicalRecord> PhysiologicalRecords { get; set; } = new List<PhysiologicalRecord>();

    public virtual UserAccount RecordedByNavigation { get; set; }
}