// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class Hospital
{
    public int HospitalId { get; set; }

    public string HospitalName { get; set; }

    public string Address { get; set; }

    public string ContactInfo { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<DoctorHospital> DoctorHospitals { get; set; } = new List<DoctorHospital>();
}