// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class Milestone
{
    public int MilestoneId { get; set; }

    public string MilestoneName { get; set; }

    public string Description { get; set; }

    public string Importance { get; set; }

    public string Category { get; set; }

    public int? MinAge { get; set; }

    public int? MaxAge { get; set; }

    public bool IsPersonal { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ChildMilestone> ChildMilestones { get; set; } = new List<ChildMilestone>();
}