// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class NutritionalRecord
{
    public int NutritionalRecordId { get; set; }

    public int RecordId { get; set; }

    public string NutritionalStatus { get; set; }

    public double? FerritinLevel { get; set; }

    public double? Triglycerides { get; set; }

    public double? BloodSugarLevel { get; set; }

    public string PhysicalActivityLevel { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual GrowthRecord Record { get; set; }
}