// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class PhysiologicalRecord
{
    public int PhysiologicalRecordId { get; set; }

    public int RecordId { get; set; }

    public int? HeartRate { get; set; }

    public double? BloodPressure { get; set; }

    public double? BodyTemperature { get; set; }

    public double? OxygenSaturation { get; set; }

    public double? SleepDuration { get; set; }

    public string Vision { get; set; }

    public string Hearing { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual GrowthRecord Record { get; set; }
}