// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class Promotion
{
    public Guid PromotionId { get; set; }

    public string PromotionCode { get; set; }

    public string Description { get; set; }

    public int DiscountPercent { get; set; }

    public decimal? MinPurchaseAmount { get; set; }

    public decimal? MaxDiscountAmount { get; set; }

    public string ApplicablePackageIds { get; set; }

    public string TargetAudience { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string Status { get; set; }

    public int? RedemptionCount { get; set; }

    public int? UsageLimit { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid ModifiedBy { get; set; }

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual UserAccount ModifiedByNavigation { get; set; }

    public virtual ICollection<PackagePromotion> PackagePromotions { get; set; } = new List<PackagePromotion>();
}