// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BabyHaven.Repositories.Models;

public partial class RatingFeedback
{
    [Key]
    public int FeedbackId { get; set; }

    public Guid UserId { get; set; }

    public int ResponseId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime FeedbackDate { get; set; }

    public string FeedbackType { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ConsultationResponse Response { get; set; }

    public virtual UserAccount User { get; set; }
}