// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class Transaction
{
    public Guid TransactionId { get; set; }

    public Guid UserId { get; set; }

    public Guid MemberMembershipId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string TransactionType { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime TransactionDate { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string GatewayTransactionId { get; set; }

    public string PaymentStatus { get; set; }

    public string Description { get; set; }

    public virtual MemberMembership MemberMembership { get; set; }

    public virtual UserAccount User { get; set; }
}