// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BabyHaven.Repositories.Models;

public partial class UserAccount
{
    public Guid UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Address { get; set; }

    public string Password { get; set; }

    public DateTime RegistrationDate { get; set; }

    public DateTime? LastLogin { get; set; }

    public byte[] ProfilePicture { get; set; }

    public string Status { get; set; }

    public string VerificationCode { get; set; }

    public bool? IsVerified { get; set; }

    public int RoleId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    public virtual ICollection<Doctor> Doctors { get; set; } = new List<Doctor>();

    public virtual Member Member { get; set; }

    public virtual ICollection<Promotion> PromotionCreatedByNavigations { get; set; } = new List<Promotion>();

    public virtual ICollection<Promotion> PromotionModifiedByNavigations { get; set; } = new List<Promotion>();

    public virtual ICollection<RatingFeedback> RatingFeedbacks { get; set; } = new List<RatingFeedback>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}